---
- name: sshd config - AuthenticationMethods
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^(#AuthenticationMethods|AuthenticationMethods)"
    line: AuthenticationMethods "publickey,keyboard-interactive""password,keyboard-interactive"
  when: ssh_auth

- name: sshd config - UsePAM
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^UsePAM"
    line: UsePAM yes
