---
- name: Add repository
  yum_repository:
    name: duosecurity
    description: Duo Security Repository
    baseurl: https://pkg.duosecurity.com/RedHat/$releasever/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://duo.com/DUO-GPG-PUBLIC-KEY.asc

- name: Install Duo Unix
  yum:
    name: duo_unix
    state: latest

